controllers/ToolsController.php
<?php

namespace app\controllers;

use api\models\DatabaseList;
use api\models\DatamartDb;
use api\models\Encryptor;
use Yii;
use yii\web\Controller;

/**
 * Default controller for the `api` module
 */
class ToolsController extends Controller
{
    public static function allowedDomains()
    {
        return [
            'http://localhost:8888',
        ];
    }
    public function behaviors()
    {
        return [
            [
                "class" => \yii\filters\ContentNegotiator::className(),
                "only" => ["tabledata", "tableschema", "test2"],
                "formats" => [
                    "application/json" => \yii\web\Response::FORMAT_JSON,
                ],

            ],
            "corsFilter" => [
                "class" => \yii\filters\Cors::className(),
                "cors" => [
                    "Origin" => static::allowedDomains(),
                    "Access-Control-Request-Method" => ['POST', 'GET'],
                    "Access-Control-Allow-Credentials" => true,
                    "Access-Control-Max-Age" => 3600,
                ],
            ],
        ];
    }
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionPostjson()
    {
        return $this->render("postjson");
    }

    public function actionDatabrowser()
    {

        $dbList = DatabaseList::find()->all();

        return $this->render("databrowser", [
            "databases" => $dbList,

        ]);
    }
    public function actionDatabase($name)
    {
        $name = base64_decode($name);
        $dbname = Encryptor::decrypt($name);

        if (!$this->isValidName($dbname)) {
            return $this->render("databasenotfound", [
                "databaseName" => $dbname,
            ]);
        }
        //  print_r($dbname);exit;
        $dbmart = new DatamartDb($dbname, false);
        if ($dbmart->isExists == false) {
            return $this->render("databasenotfound", [
                "databaseName" => $dbname,
            ]);
        }
        $tableNames = $dbmart->schema->getTableNames();
        $firsttable = null;
        if (sizeof($tableNames) > 0) {
            $firsttable = $tableNames[0];
        }

        return $this->render("database", [
            "tableNames" => $tableNames,
            "databaseName" => $dbname,
        ]);

    }

    public function actionTabledata($name)
    {
        $name = base64_decode($name);
        $parameters = Encryptor::decrypt($name);
        $pattern = "/db:(?<db>[a-zA-Z0-9_$]+);tbl:(?<tbl>[a-zA-Z0-9_$]+)/i";
        $matches = array();
        preg_match($pattern, $parameters, $matches);
        $dbname = array_key_exists("db", $matches) ? $matches["db"] : null;
        $tablename = array_key_exists("db", $matches) ? $matches["tbl"] : null;

        if ($dbname == null || $tablename == null) {
            return ["success" => false,
                "data" => "<strong>Oops!</strong>  Something wrong occured: table not found."];
        }
        if (!$this->isValidName($dbname) && !$this->isValidName($dbname)) {
            return ["success" => false,
                "data" => "<strong>Oops!</strong>  Something wrong occured: table not found."];
        }
        $db = new DatamartDb($dbname);

        $query = (new \yii\db\Query());
        $result = $query->from($tablename)->all($db);
        return ["data" => $result, "success" => true];
    }

    public function actionTableschema($name)
    {
        $name = base64_decode($name);
        $parameters = Encryptor::decrypt($name);
        $pattern = "/db:(?<db>[a-zA-Z0-9_$]+);tbl:(?<tbl>[a-zA-Z0-9_$]+)/i";
        $matches = array();
        preg_match($pattern, $parameters, $matches);
        $dbname = array_key_exists("db", $matches) ? $matches["db"] : null;
        $tablename = array_key_exists("db", $matches) ? $matches["tbl"] : null;

        if ($dbname == null || $tablename == null) {
            return ["success" => false,
                "data" => "<strong>Oops!</strong>  Something wrong occured: table not found."];
        }
        if (!$this->isValidName($dbname) && !$this->isValidName($dbname)) {
            return ["success" => false,
                "data" => "<strong>Oops!</strong>  Something wrong occured: table not found."];
        }
        $db = new DatamartDb($dbname);
        $tableSchema = $db->schema->getTableSchema($tablename);
        $tablecolumns = array_keys($tableSchema->columns);
        return ["success" => true, "data" => $tablecolumns];
    }

    private function isValidName($text)
    {
        return preg_match('/^[0-9a-zA-Z$_]+$/i', $text) != 0;
    }

    public function actionTest2()
    {

        $arr = ["2005-01-01 12:00", "2005-01-01 13:00", "2005-01-01", "2005-01-01 23:59"];
        $arr = ["123.3500", "355.00", "123.534"];
        $arr = ["true", "false", "true"];
        return $this->getColumnType($arr);
    }

    private function getColumnType($arr)
    {
        $size = sizeof($arr);
        $size = $size > 100 ? 100 : $size;
        $test_array = array_slice($arr, 0, $size);

        $date_pattern = '/^\d{4}[\-.]\d{1,2}[\-.]\d{1,2}$/';
        $datetime_pattern = '/^\d{4}[\-.]\d{1,2}[\-.]\d{1,2}\s\d{1,2}:\d{1,2}[:\d{1,2}]$/';
        $float_pattern = '/^\d+\.\d+$/i';
        $int_pattern = '/^\d+$/i';
        $boolean_pattern = '/^true|false$/i';

        $patterns = ["datetime" => $datetime_pattern, "date" => $date_pattern,
            "float" => $float_pattern, "int" => $int_pattern,
            "boolean" => $boolean_pattern];

        $result = '';
        $presult = [];
        foreach ($patterns as $pattern => $value) {
            $grep = preg_grep($value, $test_array);
            $presult[$pattern] = $grep;

            if (sizeof($grep) == $size) {
                $result = $pattern;
                break;
            }

        }

        if ($result == '') {
            $result = 'string';
        }

        return $presult;

    }

}

views/tools/database.php
<?php
use api\models\Encryptor;
use app\assets\DatatableNetAsset;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

DatatableNetAsset::register($this);
$this->registerJsFile('@web/js/databrowser.js',
    ['depends' => [app\assets\DatatableNetAsset::className()]]
);
$this->registerJsFile('@web/js/inlinealert.js',
    ['depends' => [app\assets\DatatableNetAsset::className()]]
);
$this->title = "Database";
$this->params['breadcrumbs'][] = ['label' => 'Data Browser', 'url' => ['tools/databrowser']];
$this->params['breadcrumbs'][] = $databaseName;

$pageInfo = [
    "requestUrl" => [
        "tableschema" => Url::to(["tools/tableschema"]),
        "tabledata" => Url::to(["tools/tabledata"]),

    ],
];

$this->registerJs(
    "var pageInfo=" . \yii\helpers\Json::htmlEncode($pageInfo) . ";",
    View::POS_HEAD,
    'yiiOptions'
);

?>

<h3>Database: <?=$databaseName;?></h3>
<div class="row mb-4">
    <div class="col-sm-3">
        <h5>Tables</h5>
        <div class="list-group">

            <?php
foreach ($tableNames as $tableName) {
    $qparam = implode(";", [
        "db:" . $databaseName,
        "tbl:" . $tableName,
    ]);

    echo Html::a($tableName, ["tools/tableschema", "name" => base64_encode(Encryptor::encrypt($qparam))],
        ["class" => "tablenamelink list-group-item list-group-item-action"]), "\n";
}

?>

        </div>

    </div>
    <div class="col-sm-9">
            <h5>Data</h5>
            <div id="tablePlaceholder" class="table-responsive">
            </div>

        </div>
</div>

views/tools/databasenotfound.php
<?php
use yii\web\View;
use yii\helpers\Html;
use rmrevin\yii\fontawesome\FAS;
$this->title = "Database Not Found!";

?>
<div class="row">
    <div class="col-sm-12">
        <div class="error-template">
            <h1>
                Oops!</h1>
            <h2>
                Database Not Found!</h2>
            <div class="error-details">
                Sorry, Database <?=$databaseName;?> doesn't exist
            </div>
            <div class="error-actions">
                <?=Html::a(FAS::icon("database") . " Databrowser",["tools/databrowser"],
            ["class"=>"btn btn-primary btn-lg"]);?>
                <?=Html::a(FAS::icon("envelope") . " Contact Support",["site/contact"],
            ["class"=>"btn btn-primary btn-lg"]);?>


            </div>
        </div>
    </div>
</div>

views/tools/databrowser.php
<?php
use api\models\Encryptor;
use rmrevin\yii\fontawesome\FAS;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
$this->title = "Data Browser";

$this->registerJsFile('@web/js/databrowser.js',
    ['depends' => [app\assets\DatatableNetAsset::className()]]
);

$pageInfo = [
    "requestUrl" => [
        "tableschema" => Url::to(["tools/tableschema"]),
        "tabledata" => Url::to(["tools/tabledata"]),

    ],
];

$this->registerJs(
    "var pageInfo=" . \yii\helpers\Json::htmlEncode($pageInfo) . ";",
    View::POS_HEAD,
    'yiiOptions'
);

$this->params['breadcrumbs'][] = $this->title;

?>

<h3>Data Browser</h3>

<div class="row">

    <?php
foreach ($databases as $database) {
    $databasename = str_replace("datamart_", "", $database->database_name)
    ?><div class="col-xl-4 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2 bg-light">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
                            <?=$databasename;?>
                        </div>
                        <dl class="row">
                            <dt class="col-sm-4">Created</dt>
                            <dd class="col-sm-8"><?=$database->createdAt;?></dd>
                            <dt class="col-sm-4">Owner</dt>
                            <dd class="col-sm-8"> <?=$database->owner;?></dd>
                            <dt class="col-sm-4">Description</dt>
                            <dd class="col-sm-8"> <?=$database->description;?></dd>
                        </dl>

                        <?=Html::a("Open", ["tools/database", "name" => base64_encode(Encryptor::encrypt($databasename))],
        ["class" => "databasenamelink btn btn-primary"]), "\n";?>
                    </div>
                    <div class="col-auto">
                        <?=FAS::icon("database", ["class" => 'text-gray'])->size(FAS::SIZE_3X);?>
                    </div>
                </div>




            </div>
        </div>
    </div>
    <?php
}
?>


</div>

views/tools/index.php
<?php 
use yii\helpers\Html;
$this->title="Tools";

?>
<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <?=Html::a("Post json","tools/postjson");?>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <?=Html::a("Data Browser","tools/databrowser");?>
            </div>
        </div>
    </div>
</div>

views/tools/postjson.php
<?php
$this->title = " Index ";

$this->registerJsFile(
   '@web/js/test_post.js',
   ['depends' => [\yii\web\JqueryAsset::className()]]
);
?>

<div class="api-default-index mt-4">
   <h2>Post Json</h2>
   <h4>Post Json data </h4>
</div>
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            <label for="jsonInput">Json</label>
            <textarea class="form-control border" id="jsonInput" autocomplete="off"
                style='height:400px;max-height:400px!important;white-space:pre;oveflow:auto;resize:horizontal'
                rows="20"></textarea>
        </div>
    </div>
    <div class="col-sm-6">
      <pre id = "responseBody" class="border" style='height:400px;overflow:horizontal;'>
      </pre>
    </div>
</div>

<button class="btn btn-primary" id="btnPost">Post</button>